#!/bin/sh

set -x

SOURCE_DIR=`pwd`
BUILD_DIR=${BUILD_DIR:-./build}
BUILD_TYPE=${BUILD_TYPE:-debug}
INSTALL_DIR=${INSTALL_DIR:-../${BUILD_TYPE}-install}
LOGLIB=${LOGLIB:-}
BUILD_TEST=${BUILD_TEST:-ON}
BUILD_UNITTEST=${BUILD_UNITTEST:-OFF}

mkdir -p $BUILD_DIR/$BUILD_TYPE \
	&& cd $BUILD_DIR/$BUILD_TYPE \
	&& cmake \
		-DCMAKE_BUILD_TYPE=$BUILD_TYPE \
		-DCMAKE_INSTALL_PREFIX=$INSTALL_DIR \
		-DBUILD_TEST=$BUILD_TEST \
		-DBUILD_UNITTEST=$BUILD_UNITTEST \
		-DLOGLIB=$LOGLIB \
		$SOURCE_DIR \
	&& make $*	
